import os

os.environ.get('FACEBOOK')

def site_settings_processor(request):
	context_dictionary = {
		'root_url': 'SOSPoolRescue.com',
		'admin_name': 'admin',
		'company_name': 'SOS Pool Rescue',
		'company_short': 'SOS',
		'footer_copyright': 'SurgeSite, 2015',
		'logo_file_name': 'images/sos.jpg',
		'site_email': 'jared@SurgeSite.com',
		# if email changes, update misc_pages/email.html
		'company_phone_text': '480-309-3181',
		'company_phone_link': '14803093181',
		'company_address': 'Address Unknown',
		'yelp_id': '',
		'google_plus_url': 'https://plus.google.com/u/0/b/101072122455137245100',
		'fb_fan_page_url': 'https://www.facebook.com/azspraypros',
		'fb_app_id': '442602292564761',
		'meta_content': 'Phoenix area Emergency Pool and Home Repair, Pool Cleaning, and Handyman Services',
		'navbar_link1_name': 'services',
		'navbar_link1_text': 'Services',
		'navbar_link2_name': 'about',
		'navbar_link2_text': 'About',
		'navbar_link3_name': 'contact',
		'navbar_link3_text': 'Contact',
		'sublink1_name': 'pool_repair',
		'sublink1_text': 'Pool Repair',
		'sublink2_name': 'pool_service',
		'sublink2_text': 'Pool Service',
		'sublink3_name': 'handyman',
		'sublink3_text': 'Handyman Services',
		'call_to_action_button_text': 'Contact us today',
		'call_to_action_text': "to learn the 5 things your pool guy isn't telling you.",
		'user_cta_text': "Tell us a little more",
		'user_cta_button': "about YOU",
		'user_cta_link': 'profiles_profile_detail',
		'main_image_file': 'images/pool_cleaner.jpg',
		'main_image_header_text': "",
		'main_image_content_text': 'Pool ownership simplified. You use it, we do the rest.',
		'main_image_button_text': "Free Consultation",
		'main_image_button_link_name': 'contact',
		'homepage_content_top': 'Header explaining company',
		'homepage_content_quote': '"An optional quote from one of your customers"',
		 'homepage_content_quote_name': 'John D',
		'img1_file': 'images/red_checkmark.jpg',
		'img1_alt': 'Pool Repair',
		'img1_title': 'Pool Repair',
		'img1_text': "Text about pool repair",
		'img1_link_name': 'pool_repair',
		'img2_file': 'images/red_checkmark.jpg',
		'img2_alt': 'Weekly pool service',
		'img2_title': 'Pool Cleaning',
		'img2_text': "Text about pool cleaning services",
		'img1_is_popup': False,
		'img2_is_modal': False,
		'img2_link_name': 'pool_service',
		'img3_file': 'images/red_checkmark.jpg',
		'img3_alt': 'Home Repairs',
		'img3_title': 'Home Repair',
		'img3_text': "Text about handyman services",
		'img3_link_name': 'handyman',
		'default_testimonial': '"An optional quote from one of your customers!"',
		'testimonial_name': 'John D.',
		'unique_content_title': 'Instant 10% Discount!',
		'unique_content_text': 'Sign up today and receive a coupon for a 10% discount on your next service. Also receive exclusive monthly offers and newsletter.',
		'unique_content_link_name': 'registration_register',
		'unique_content_button_text': 'Sign Up Now',
	}
	return(context_dictionary)